#' Title FilterData
#' This function removes contaminant peptides and untrusted peptides from the initialized data list.
#'
#' @param Peptide Quantitative peptide information generated by Initiation function
#' @param type a vector describe the subtype of samples
#' @param A A type name of cells for comparison
#' @param B A type name of cells for comparison
#' @param Contamination Accession markers that annotate a contaminant peptide
#' @param rmKRT T or F, Whether to remove keratin protein or not
#' @param rmTRY T or F, Whether to remove trypsin protein or not
#' @param NAThres Maximum percentage of missing values allowed for each peptide
#'
#' @return A data list of peptide information without untrusted information
#'
#' @examples
#' Peptide<-Initiation(test_raw)
#' Peptide<-FilterData(Peptide,type=test_type,'A','B')
FilterData<-function (Peptide, type, A, B, Contamination = "CON",
                      rmKRT = TRUE, rmTRY = TRUE,NAThres = 0.6)
{
  if ("Peak" %in% names(Peptide)) {
    Match <- TRUE
  }
  else {
    Match <- FALSE
  }
  SelectContamination <- function(Description) {
    CON <- rownames(Description)[grep(Contamination, Description$Accession)]
    if(rmKRT){CON <- c(CON, rownames(Description)[grep("Keratin",
                                                       Description$Description)])}
    if(rmTRY){CON <- c(CON, rownames(Description)[grep("Trypsin",
                                                       Description$Description)])}
    return(CON)
  }
  FilterNA <- function(abu, percent, type, A, B) {
    abu <- abu[, type == A | type == B]
    target <- rownames(abu)[apply(abu, 1, function(x) sort(x)[ceiling(length(x) *
                                                                        percent)] == 0)]
    return(target)
  }
  RemoveFiltered <- function(target, Peptide) {
    Peptide$key <- Peptide$key[!rownames(Peptide$key) %in%
                                 target, ]
    Peptide$Abu <- Peptide$Abu[rownames(Peptide$key), ]
    Peptide$Description <- Peptide$Description[rownames(Peptide$key),
    ]
    Peptide$Peak <- Peptide$Peak[rownames(Peptide$key),
    ]
    return(Peptide)
  }
  MatchFilter <- function(Peptide, CON) {
    CON <- Peptide$Peak[CON, ]
    Peptide <- RemoveFiltered(target = CON, Peptide = Peptide)
    fit_total <- MASS::fitdistr(apply(Peptide$Abu, 1, sum),
                                "normal")
    max_total <- fit_total$estimate[1] + 3 * fit_total$estimate[2]
    fit_CV <- MASS::fitdistr(apply(Peptide$Abu, 1, function(x) stats::sd(x)/mean(x)),
                             "normal")
    max_CV <- fit_CV$estimate[1] + 3 * fit_CV$estimate[2]
    target <- rownames(Peptide$Abu)[apply(Peptide$Abu, 1,
                                          sum) > max_total | apply(Peptide$Abu, 1, function(x) stats::sd(x)/mean(x)) >
                                      max_CV]
    target <- target[apply(Peptide$Peak[target, ], 1, function(x) sum(abs(CON[,
                                                                              1] - x[1]) < 0.05 & abs(CON[, 2] - x[2]) < 2)) >
                       0]
    return(target)
  }
  Filtered_NA <- Peptide$key[FilterNA(Peptide$Abu, NAThres, type,
                                      A, B), ]
  Peptide <- RemoveFiltered(rownames(Filtered_NA), Peptide)
  Filtered_CON <- SelectContamination(Peptide$Description)
  if (Match) {
    Filtered_MC <- MatchFilter(Peptide, Filtered_CON)
    Peptide <- RemoveFiltered(target = c(Filtered_CON, Filtered_MC),
                              Peptide)
  }
  else {
    Peptide <- RemoveFiltered(target = Filtered_CON, Peptide)
  }
  Peptide$Abu <- Peptide$Abu[, which(type == A | type == B)]
  type <- type[which(type == A | type == B)]
  Peptide <- list(Abu = Peptide$Abu, key = Peptide$key, type = type,
                  Description = Peptide$Description)
  return(Peptide)
}
